/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ApiRulesIdDeleteRequest
    /// </summary>
    [JsonConverter(typeof(ApiRulesIdDeleteRequestJsonConverter))]
    [DataContract(Name = "_api_Rules__id__delete_request")]
    public partial class ApiRulesIdDeleteRequest : AbstractOpenAPISchema, IEquatable<ApiRulesIdDeleteRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiRulesIdDeleteRequest" /> class
        /// with the <see cref="RuleRequest" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of RuleRequest.</param>
        public ApiRulesIdDeleteRequest(RuleRequest actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiRulesIdDeleteRequest" /> class
        /// with the <see cref="RulePostRequest" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of RulePostRequest.</param>
        public ApiRulesIdDeleteRequest(RulePostRequest actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(RulePostRequest))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(RuleRequest))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: RulePostRequest, RuleRequest");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `RuleRequest`. If the actual instance is not `RuleRequest`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of RuleRequest</returns>
        public RuleRequest GetRuleRequest()
        {
            return (RuleRequest)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `RulePostRequest`. If the actual instance is not `RulePostRequest`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of RulePostRequest</returns>
        public RulePostRequest GetRulePostRequest()
        {
            return (RulePostRequest)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiRulesIdDeleteRequest {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ApiRulesIdDeleteRequest.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ApiRulesIdDeleteRequest
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ApiRulesIdDeleteRequest</returns>
        public static ApiRulesIdDeleteRequest FromJson(string jsonString)
        {
            ApiRulesIdDeleteRequest newApiRulesIdDeleteRequest = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newApiRulesIdDeleteRequest;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(RulePostRequest).GetProperty("AdditionalProperties") == null)
                {
                    newApiRulesIdDeleteRequest = new ApiRulesIdDeleteRequest(JsonConvert.DeserializeObject<RulePostRequest>(jsonString, ApiRulesIdDeleteRequest.SerializerSettings));
                }
                else
                {
                    newApiRulesIdDeleteRequest = new ApiRulesIdDeleteRequest(JsonConvert.DeserializeObject<RulePostRequest>(jsonString, ApiRulesIdDeleteRequest.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("RulePostRequest");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into RulePostRequest: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(RuleRequest).GetProperty("AdditionalProperties") == null)
                {
                    newApiRulesIdDeleteRequest = new ApiRulesIdDeleteRequest(JsonConvert.DeserializeObject<RuleRequest>(jsonString, ApiRulesIdDeleteRequest.SerializerSettings));
                }
                else
                {
                    newApiRulesIdDeleteRequest = new ApiRulesIdDeleteRequest(JsonConvert.DeserializeObject<RuleRequest>(jsonString, ApiRulesIdDeleteRequest.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("RuleRequest");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into RuleRequest: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newApiRulesIdDeleteRequest;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiRulesIdDeleteRequest);
        }

        /// <summary>
        /// Returns true if ApiRulesIdDeleteRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiRulesIdDeleteRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiRulesIdDeleteRequest input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ApiRulesIdDeleteRequest
    /// </summary>
    public class ApiRulesIdDeleteRequestJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ApiRulesIdDeleteRequest).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return ApiRulesIdDeleteRequest.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
