/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CropResponse
    /// </summary>
    [DataContract(Name = "CropResponse")]
    public partial class CropResponse : IEquatable<CropResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CropResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CropResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CropResponse" /> class.
        /// </summary>
        /// <param name="imageDataUrl">A DataUrl representation of the image file (Use Microsoft.IdentityModel.Tokens.Base64UrlEncoder to decode.) (required).</param>
        public CropResponse(string imageDataUrl = default(string))
        {
            // to ensure "imageDataUrl" is required (not null)
            if (imageDataUrl == null)
            {
                throw new ArgumentNullException("imageDataUrl is a required property for CropResponse and cannot be null");
            }
            this.ImageDataUrl = imageDataUrl;
        }

        /// <summary>
        /// A DataUrl representation of the image file (Use Microsoft.IdentityModel.Tokens.Base64UrlEncoder to decode.)
        /// </summary>
        /// <value>A DataUrl representation of the image file (Use Microsoft.IdentityModel.Tokens.Base64UrlEncoder to decode.)</value>
        [DataMember(Name = "imageDataUrl", IsRequired = true, EmitDefaultValue = true)]
        public string ImageDataUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CropResponse {\n");
            sb.Append("  ImageDataUrl: ").Append(ImageDataUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CropResponse);
        }

        /// <summary>
        /// Returns true if CropResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CropResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CropResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ImageDataUrl == input.ImageDataUrl ||
                    (this.ImageDataUrl != null &&
                    this.ImageDataUrl.Equals(input.ImageDataUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ImageDataUrl != null)
                {
                    hashCode = (hashCode * 59) + this.ImageDataUrl.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // ImageDataUrl (string) minLength
            if (this.ImageDataUrl != null && this.ImageDataUrl.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ImageDataUrl, length must be greater than 1.", new [] { "ImageDataUrl" });
            }

            yield break;
        }
    }

}
