/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DatasetPostRequest
    /// </summary>
    [DataContract(Name = "DatasetPostRequest")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(DatasetPostRequest), "DatasetPostRequest")]
    [JsonSubtypes.KnownSubType(typeof(DatasetRequest), "DatasetRequest")]
    public partial class DatasetPostRequest : DatasetRequest, IEquatable<DatasetPostRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetPostRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DatasetPostRequest() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetPostRequest" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="payloadId">The payload identifier to attach (required).</param>
        /// <param name="type">type (required) (default to &quot;DatasetPostRequest&quot;).</param>
        /// <param name="localizedNames">Localized dataset name.</param>
        /// <param name="description">The dataset description.</param>
        /// <param name="ruleIds">The rule identifier(s) to attach.</param>
        /// <param name="viewableByAssociatedUserTypes">A comma separated list of associated user types permitted to view this dataset    The value can be:  - None  - Holder  - Coholder.</param>
        public DatasetPostRequest(string name = default(string), Guid payloadId = default(Guid), string type = "DatasetPostRequest", string localizedNames = default(string), string description = default(string), List<Guid> ruleIds = default(List<Guid>), ViewableByAssociatedUserTypesEnum? viewableByAssociatedUserTypes = default(ViewableByAssociatedUserTypesEnum?)) : base(type, name, localizedNames, description, payloadId, ruleIds, viewableByAssociatedUserTypes)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for DatasetPostRequest and cannot be null");
            }
            this.Name = name;
            this.PayloadId = payloadId;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The payload identifier to attach
        /// </summary>
        /// <value>The payload identifier to attach</value>
        [DataMember(Name = "payloadId", IsRequired = true, EmitDefaultValue = true)]
        public Guid PayloadId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DatasetPostRequest {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PayloadId: ").Append(PayloadId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DatasetPostRequest);
        }

        /// <summary>
        /// Returns true if DatasetPostRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of DatasetPostRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DatasetPostRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) &&
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && base.Equals(input) &&
                (
                    this.PayloadId == input.PayloadId ||
                    (this.PayloadId != null &&
                    this.PayloadId.Equals(input.PayloadId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.PayloadId != null)
                {
                    hashCode = (hashCode * 59) + this.PayloadId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new[] { "Name" });
            }

            yield break;
        }
    }
}