/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// FingerTypesVerifyContent
    /// </summary>
    [DataContract(Name = "FingerTypesVerifyContent")]
    public partial class FingerTypesVerifyContent : IEquatable<FingerTypesVerifyContent>, IValidatableObject
    {
        /// <summary>
        /// The content type
        /// </summary>
        /// <value>The content type</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum FingerLeftThumb for value: FingerLeftThumb
            /// </summary>
            [EnumMember(Value = "FingerLeftThumb")]
            FingerLeftThumb = 1,

            /// <summary>
            /// Enum FingerLeftIndexFinger for value: FingerLeftIndexFinger
            /// </summary>
            [EnumMember(Value = "FingerLeftIndexFinger")]
            FingerLeftIndexFinger = 2,

            /// <summary>
            /// Enum FingerLeftMiddleFinger for value: FingerLeftMiddleFinger
            /// </summary>
            [EnumMember(Value = "FingerLeftMiddleFinger")]
            FingerLeftMiddleFinger = 3,

            /// <summary>
            /// Enum FingerLeftRingFinger for value: FingerLeftRingFinger
            /// </summary>
            [EnumMember(Value = "FingerLeftRingFinger")]
            FingerLeftRingFinger = 4,

            /// <summary>
            /// Enum FingerLeftLittleFinger for value: FingerLeftLittleFinger
            /// </summary>
            [EnumMember(Value = "FingerLeftLittleFinger")]
            FingerLeftLittleFinger = 5,

            /// <summary>
            /// Enum FingerRightThumb for value: FingerRightThumb
            /// </summary>
            [EnumMember(Value = "FingerRightThumb")]
            FingerRightThumb = 6,

            /// <summary>
            /// Enum FingerRightIndexFinger for value: FingerRightIndexFinger
            /// </summary>
            [EnumMember(Value = "FingerRightIndexFinger")]
            FingerRightIndexFinger = 7,

            /// <summary>
            /// Enum FingerRightMiddleFinger for value: FingerRightMiddleFinger
            /// </summary>
            [EnumMember(Value = "FingerRightMiddleFinger")]
            FingerRightMiddleFinger = 8,

            /// <summary>
            /// Enum FingerRightRingFinger for value: FingerRightRingFinger
            /// </summary>
            [EnumMember(Value = "FingerRightRingFinger")]
            FingerRightRingFinger = 9,

            /// <summary>
            /// Enum FingerRightLittleFinger for value: FingerRightLittleFinger
            /// </summary>
            [EnumMember(Value = "FingerRightLittleFinger")]
            FingerRightLittleFinger = 10

        }


        /// <summary>
        /// The content type
        /// </summary>
        /// <value>The content type</value>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FingerTypesVerifyContent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FingerTypesVerifyContent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FingerTypesVerifyContent" /> class.
        /// </summary>
        /// <param name="files">The binary files containing the content (required).</param>
        /// <param name="type">The content type.</param>
        public FingerTypesVerifyContent(List<System.IO.Stream> files = default(List<System.IO.Stream>), TypeEnum? type = default(TypeEnum?))
        {
            // to ensure "files" is required (not null)
            if (files == null)
            {
                throw new ArgumentNullException("files is a required property for FingerTypesVerifyContent and cannot be null");
            }
            this.Files = files;
            this.Type = type;
        }

        /// <summary>
        /// The binary files containing the content
        /// </summary>
        /// <value>The binary files containing the content</value>
        [DataMember(Name = "files", IsRequired = true, EmitDefaultValue = true)]
        public List<System.IO.Stream> Files { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FingerTypesVerifyContent {\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FingerTypesVerifyContent);
        }

        /// <summary>
        /// Returns true if FingerTypesVerifyContent instances are equal
        /// </summary>
        /// <param name="input">Instance of FingerTypesVerifyContent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FingerTypesVerifyContent input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Files == input.Files ||
                    this.Files != null &&
                    input.Files != null &&
                    this.Files.SequenceEqual(input.Files)
                ) && 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Files != null)
                {
                    hashCode = (hashCode * 59) + this.Files.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
