/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A circle shaped geofence
    /// </summary>
    [DataContract(Name = "GeofenceCircleData")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(GeofenceCircleData), "GeofenceCircleData")]
    [JsonSubtypes.KnownSubType(typeof(GeofencePolygonData), "GeofencePolygonData")]
    [JsonSubtypes.KnownSubType(typeof(GeofenceRectangleData), "GeofenceRectangleData")]
    public partial class GeofenceCircleData : GeofenceData, IEquatable<GeofenceCircleData>, IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum None for value: None
            /// </summary>
            [EnumMember(Value = "None")]
            None = 1,

            /// <summary>
            /// Enum Rectangle for value: Rectangle
            /// </summary>
            [EnumMember(Value = "Rectangle")]
            Rectangle = 2,

            /// <summary>
            /// Enum Polygon for value: Polygon
            /// </summary>
            [EnumMember(Value = "Polygon")]
            Polygon = 3,

            /// <summary>
            /// Enum Circle for value: Circle
            /// </summary>
            [EnumMember(Value = "Circle")]
            Circle = 4
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeofenceCircleData" /> class.
        /// </summary>
        /// <param name="center">center.</param>
        /// <param name="radius">The radius of the circle, in meters.</param>
        public GeofenceCircleData(Coordinate center = default(Coordinate), double radius = default(double)) : base()
        {
            this.Center = center;
            this.Radius = radius;
            this.Type = TypeEnum.Circle;
        }

        /// <summary>
        /// Gets or Sets Center
        /// </summary>
        [DataMember(Name = "center", EmitDefaultValue = false)]
        public Coordinate Center { get; set; }

        /// <summary>
        /// The radius of the circle, in meters
        /// </summary>
        /// <value>The radius of the circle, in meters</value>
        [DataMember(Name = "radius", EmitDefaultValue = false)]
        public double Radius { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeofenceCircleData {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Center: ").Append(Center).Append("\n");
            sb.Append("  Radius: ").Append(Radius).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GeofenceCircleData);
        }

        /// <summary>
        /// Returns true if GeofenceCircleData instances are equal
        /// </summary>
        /// <param name="input">Instance of GeofenceCircleData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GeofenceCircleData input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) &&
                (
                    this.Center == input.Center ||
                    (this.Center != null &&
                    this.Center.Equals(input.Center))
                ) && base.Equals(input) &&
                (
                    this.Radius == input.Radius ||
                    this.Radius.Equals(input.Radius)
                ) && base.Equals(input) &&
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Center != null)
                {
                    hashCode = (hashCode * 59) + this.Center.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Radius.GetHashCode();
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }
}