/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SmacRequest
    /// </summary>
    [DataContract(Name = "SmacRequest")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(SmacPostRequest), "SmacPostRequest")]
    [JsonSubtypes.KnownSubType(typeof(SmacRequest), "SmacRequest")]
    public partial class SmacRequest : IEquatable<SmacRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SmacRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SmacRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SmacRequest" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="name">The SMAC name.</param>
        /// <param name="description">The SMAC description.</param>
        /// <param name="datasets">The dataset identifiers to attach.</param>
        /// <param name="associatedUsers">The list of associated users.</param>
        public SmacRequest(string type = default(string), string name = default(string), string description = default(string), List<Guid> datasets = default(List<Guid>), List<AssociatedUser> associatedUsers = default(List<AssociatedUser>))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for SmacRequest and cannot be null");
            }
            this.Type = type;
            this.Name = name;
            this.Description = description;
            this.Datasets = datasets;
            this.AssociatedUsers = associatedUsers;
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// The SMAC name
        /// </summary>
        /// <value>The SMAC name</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The SMAC description
        /// </summary>
        /// <value>The SMAC description</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// The dataset identifiers to attach
        /// </summary>
        /// <value>The dataset identifiers to attach</value>
        [DataMember(Name = "datasets", EmitDefaultValue = true)]
        public List<Guid> Datasets { get; set; }

        /// <summary>
        /// The list of associated users
        /// </summary>
        /// <value>The list of associated users</value>
        [DataMember(Name = "associatedUsers", EmitDefaultValue = true)]
        public List<AssociatedUser> AssociatedUsers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SmacRequest {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Datasets: ").Append(Datasets).Append("\n");
            sb.Append("  AssociatedUsers: ").Append(AssociatedUsers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SmacRequest);
        }

        /// <summary>
        /// Returns true if SmacRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SmacRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SmacRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Datasets == input.Datasets ||
                    this.Datasets != null &&
                    input.Datasets != null &&
                    this.Datasets.SequenceEqual(input.Datasets)
                ) && 
                (
                    this.AssociatedUsers == input.AssociatedUsers ||
                    this.AssociatedUsers != null &&
                    input.AssociatedUsers != null &&
                    this.AssociatedUsers.SequenceEqual(input.AssociatedUsers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.Datasets != null)
                {
                    hashCode = (hashCode * 59) + this.Datasets.GetHashCode();
                }
                if (this.AssociatedUsers != null)
                {
                    hashCode = (hashCode * 59) + this.AssociatedUsers.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
