/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SmacGenerateRequest
    /// </summary>
    [DataContract(Name = "SmacGenerateRequest")]
    public partial class SmacGenerateRequest : IEquatable<SmacGenerateRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SmacGenerateRequest" /> class.
        /// </summary>
        /// <param name="metadatas">metadatas.</param>
        public SmacGenerateRequest(List<SmacGenerateRequestMetadatasInner> metadatas = default(List<SmacGenerateRequestMetadatasInner>))
        {
            this.Metadatas = metadatas;
        }

        /// <summary>
        /// Gets or Sets Metadatas
        /// </summary>
        [DataMember(Name = "metadatas", EmitDefaultValue = true)]
        public List<SmacGenerateRequestMetadatasInner> Metadatas { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SmacGenerateRequest {\n");
            sb.Append("  Metadatas: ").Append(Metadatas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SmacGenerateRequest);
        }

        /// <summary>
        /// Returns true if SmacGenerateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SmacGenerateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SmacGenerateRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Metadatas == input.Metadatas ||
                    this.Metadatas != null &&
                    input.Metadatas != null &&
                    this.Metadatas.SequenceEqual(input.Metadatas)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Metadatas != null)
                {
                    hashCode = (hashCode * 59) + this.Metadatas.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
