/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A user role rule
    /// </summary>
    [DataContract(Name = "UserRoleRule")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(DateTimeRule), "DateTimeRule")]
    [JsonSubtypes.KnownSubType(typeof(EmailRule), "EmailRule")]
    [JsonSubtypes.KnownSubType(typeof(LocationRule), "LocationRule")]
    [JsonSubtypes.KnownSubType(typeof(ScanOptionRule), "ScanOptionRule")]
    [JsonSubtypes.KnownSubType(typeof(UserRoleRule), "UserRoleRule")]
    public partial class UserRoleRule : BaseRule, IEquatable<UserRoleRule>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRoleRule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserRoleRule() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRoleRule" /> class.
        /// </summary>
        /// <param name="userRoles">A comma or semicolon separated string defining the user roles to include.</param>
        /// <param name="isInverse">True, to turn this rule into block rule.</param>
        /// <param name="type">Defines the type of the rule (required) (default to &quot;UserRoleRule&quot;).</param>
        public UserRoleRule(List<string> userRoles = default(List<string>), bool? isInverse = default(bool?), string type = "UserRoleRule") : base()
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for UserRoleRule and cannot be null");
            }
            this.Type = type;
            this.UserRoles = userRoles;
            this.IsInverse = isInverse;
        }

        /// <summary>
        /// A comma or semicolon separated string defining the user roles to include
        /// </summary>
        /// <value>A comma or semicolon separated string defining the user roles to include</value>
        [DataMember(Name = "userRoles", EmitDefaultValue = true)]
        public List<string> UserRoles { get; set; }

        /// <summary>
        /// True, to turn this rule into block rule
        /// </summary>
        /// <value>True, to turn this rule into block rule</value>
        [DataMember(Name = "isInverse", EmitDefaultValue = true)]
        public bool? IsInverse { get; set; }

        /// <summary>
        /// Defines the type of the rule
        /// </summary>
        /// <value>Defines the type of the rule</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserRoleRule {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  UserRoles: ").Append(UserRoles).Append("\n");
            sb.Append("  IsInverse: ").Append(IsInverse).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserRoleRule);
        }

        /// <summary>
        /// Returns true if UserRoleRule instances are equal
        /// </summary>
        /// <param name="input">Instance of UserRoleRule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserRoleRule input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.UserRoles == input.UserRoles ||
                    this.UserRoles != null &&
                    input.UserRoles != null &&
                    this.UserRoles.SequenceEqual(input.UserRoles)
                ) && base.Equals(input) && 
                (
                    this.IsInverse == input.IsInverse ||
                    (this.IsInverse != null &&
                    this.IsInverse.Equals(input.IsInverse))
                ) && base.Equals(input) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.UserRoles != null)
                {
                    hashCode = (hashCode * 59) + this.UserRoles.GetHashCode();
                }
                if (this.IsInverse != null)
                {
                    hashCode = (hashCode * 59) + this.IsInverse.GetHashCode();
                }
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            // Type (string) minLength
            if (this.Type != null && this.Type.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Type, length must be greater than 1.", new [] { "Type" });
            }

            yield break;
        }
    }

}
