/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing OAuthApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OAuthApiTests : IDisposable
    {
        private OAuthApi instance;

        public OAuthApiTests()
        {
            instance = new OAuthApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OAuthApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OAuthApi
            //Assert.IsType<OAuthApi>(instance);
        }

        /// <summary>
        /// Test ApiOAuthVerifyTokenPost
        /// </summary>
        [Fact]
        public void ApiOAuthVerifyTokenPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //VerifyTokenRequest verifyTokenRequest = null;
            //var response = instance.ApiOAuthVerifyTokenPost(verifyTokenRequest);
            //Assert.IsType<VerifyTokenResponse>(response);
        }
    }
}
