/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SmacAssociatedUsersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SmacAssociatedUsersApiTests : IDisposable
    {
        private SmacAssociatedUsersApi instance;

        public SmacAssociatedUsersApiTests()
        {
            instance = new SmacAssociatedUsersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SmacAssociatedUsersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SmacAssociatedUsersApi
            //Assert.IsType<SmacAssociatedUsersApi>(instance);
        }

        /// <summary>
        /// Test SmacAssociatedUsersIdGet
        /// </summary>
        [Fact]
        public void SmacAssociatedUsersIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //string returnUrl = null;
            //instance.SmacAssociatedUsersIdGet(id, returnUrl);
        }
    }
}
