/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing UsersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UsersApiTests : IDisposable
    {
        private UsersApi instance;

        public UsersApiTests()
        {
            instance = new UsersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UsersApi
            //Assert.IsType<UsersApi>(instance);
        }

        /// <summary>
        /// Test ApiUsersAssociatedSmacsGet
        /// </summary>
        [Fact]
        public void ApiUsersAssociatedSmacsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiUsersAssociatedSmacsGet();
            //Assert.IsType<AssociatedSmacsResponse>(response);
        }

        /// <summary>
        /// Test ApiUsersAuthenticatePost
        /// </summary>
        [Fact]
        public void ApiUsersAuthenticatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AuthenticateRequest authenticateRequest = null;
            //var response = instance.ApiUsersAuthenticatePost(authenticateRequest);
            //Assert.IsType<AuthenticateResponse>(response);
        }

        /// <summary>
        /// Test ApiUsersForgotPasswordPost
        /// </summary>
        [Fact]
        public void ApiUsersForgotPasswordPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EmailRequest emailRequest = null;
            //var response = instance.ApiUsersForgotPasswordPost(emailRequest);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test ApiUsersRefreshTokenPost
        /// </summary>
        [Fact]
        public void ApiUsersRefreshTokenPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RefreshTokenRequest refreshTokenRequest = null;
            //var response = instance.ApiUsersRefreshTokenPost(refreshTokenRequest);
            //Assert.IsType<AuthenticateResponse>(response);
        }

        /// <summary>
        /// Test ApiUsersRegisterPost
        /// </summary>
        [Fact]
        public void ApiUsersRegisterPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RegisterRequest registerRequest = null;
            //var response = instance.ApiUsersRegisterPost(registerRequest);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test ApiUsersResendEmailConfirmationPost
        /// </summary>
        [Fact]
        public void ApiUsersResendEmailConfirmationPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EmailRequest emailRequest = null;
            //var response = instance.ApiUsersResendEmailConfirmationPost(emailRequest);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test ApiUsersRevokeTokenPost
        /// </summary>
        [Fact]
        public void ApiUsersRevokeTokenPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RevokeTokenRequest revokeTokenRequest = null;
            //var response = instance.ApiUsersRevokeTokenPost(revokeTokenRequest);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test ApiUsersRolesPost
        /// </summary>
        [Fact]
        public void ApiUsersRolesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiUsersRolesPost();
            //Assert.IsType<List<string>>(response);
        }

        /// <summary>
        /// Test ApiUsersUploadProfilePhotoPost
        /// </summary>
        [Fact]
        public void ApiUsersUploadProfilePhotoPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UploadPhotoRequest uploadPhotoRequest = null;
            //var response = instance.ApiUsersUploadProfilePhotoPost(uploadPhotoRequest);
            //Assert.IsType<UploadPhotoResponse>(response);
        }

        /// <summary>
        /// Test ApiUsersUserProfilePost
        /// </summary>
        [Fact]
        public void ApiUsersUserProfilePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiUsersUserProfilePost();
            //Assert.IsType<UserProfileResponse>(response);
        }
    }
}
