/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing UtilitiesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UtilitiesApiTests : IDisposable
    {
        private UtilitiesApi instance;

        public UtilitiesApiTests()
        {
            instance = new UtilitiesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UtilitiesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UtilitiesApi
            //Assert.IsType<UtilitiesApi>(instance);
        }

        /// <summary>
        /// Test ApiUtilitiesPingGet
        /// </summary>
        [Fact]
        public void ApiUtilitiesPingGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiUtilitiesPingGet();
            //Assert.IsType<PingResponse>(response);
        }

        /// <summary>
        /// Test ApiUtilitiesVersionGet
        /// </summary>
        [Fact]
        public void ApiUtilitiesVersionGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiUtilitiesVersionGet();
            //Assert.IsType<VersionResponse>(response);
        }
    }
}
