/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ApiBiometricsVerifyFingerPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiBiometricsVerifyFingerPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiBiometricsVerifyFingerPostRequest
        //private ApiBiometricsVerifyFingerPostRequest instance;

        public ApiBiometricsVerifyFingerPostRequestTests()
        {
            // TODO uncomment below to create an instance of ApiBiometricsVerifyFingerPostRequest
            //instance = new ApiBiometricsVerifyFingerPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiBiometricsVerifyFingerPostRequest
        /// </summary>
        [Fact]
        public void ApiBiometricsVerifyFingerPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiBiometricsVerifyFingerPostRequest
            //Assert.IsType<ApiBiometricsVerifyFingerPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Contents'
        /// </summary>
        [Fact]
        public void ContentsTest()
        {
            // TODO unit test for the property 'Contents'
        }

    }

}
