/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ApiBiometricsVerifyFacePostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiBiometricsVerifyFacePostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiBiometricsVerifyFacePostRequest
        //private ApiBiometricsVerifyFacePostRequest instance;

        public ApiBiometricsVerifyFacePostRequestTests()
        {
            // TODO uncomment below to create an instance of ApiBiometricsVerifyFacePostRequest
            //instance = new ApiBiometricsVerifyFacePostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiBiometricsVerifyFacePostRequest
        /// </summary>
        [Fact]
        public void ApiBiometricsVerifyFacePostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiBiometricsVerifyFacePostRequest
            //Assert.IsType<ApiBiometricsVerifyFacePostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Contents'
        /// </summary>
        [Fact]
        public void ContentsTest()
        {
            // TODO unit test for the property 'Contents'
        }

    }

}
