/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ApiSmacsIdDeleteRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiSmacsIdDeleteRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiSmacsIdDeleteRequest
        //private ApiSmacsIdDeleteRequest instance;

        public ApiSmacsIdDeleteRequestTests()
        {
            // TODO uncomment below to create an instance of ApiSmacsIdDeleteRequest
            //instance = new ApiSmacsIdDeleteRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiSmacsIdDeleteRequest
        /// </summary>
        [Fact]
        public void ApiSmacsIdDeleteRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiSmacsIdDeleteRequest
            //Assert.IsType<ApiSmacsIdDeleteRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Datasets'
        /// </summary>
        [Fact]
        public void DatasetsTest()
        {
            // TODO unit test for the property 'Datasets'
        }
        /// <summary>
        /// Test the property 'AssociatedUsers'
        /// </summary>
        [Fact]
        public void AssociatedUsersTest()
        {
            // TODO unit test for the property 'AssociatedUsers'
        }

    }

}
