/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AssociatedSmacsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssociatedSmacsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssociatedSmacsResponse
        //private AssociatedSmacsResponse instance;

        public AssociatedSmacsResponseTests()
        {
            // TODO uncomment below to create an instance of AssociatedSmacsResponse
            //instance = new AssociatedSmacsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssociatedSmacsResponse
        /// </summary>
        [Fact]
        public void AssociatedSmacsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssociatedSmacsResponse
            //Assert.IsType<AssociatedSmacsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
