/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AssociatedSmac
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssociatedSmacTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssociatedSmac
        //private AssociatedSmac instance;

        public AssociatedSmacTests()
        {
            // TODO uncomment below to create an instance of AssociatedSmac
            //instance = new AssociatedSmac();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssociatedSmac
        /// </summary>
        [Fact]
        public void AssociatedSmacInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssociatedSmac
            //Assert.IsType<AssociatedSmac>(instance);
        }


        /// <summary>
        /// Test the property 'SmacId'
        /// </summary>
        [Fact]
        public void SmacIdTest()
        {
            // TODO unit test for the property 'SmacId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Fact]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DatasetsCount'
        /// </summary>
        [Fact]
        public void DatasetsCountTest()
        {
            // TODO unit test for the property 'DatasetsCount'
        }
        /// <summary>
        /// Test the property 'ScansCount'
        /// </summary>
        [Fact]
        public void ScansCountTest()
        {
            // TODO unit test for the property 'ScansCount'
        }
        /// <summary>
        /// Test the property 'Datasets'
        /// </summary>
        [Fact]
        public void DatasetsTest()
        {
            // TODO unit test for the property 'Datasets'
        }
        /// <summary>
        /// Test the property 'QrCode'
        /// </summary>
        [Fact]
        public void QrCodeTest()
        {
            // TODO unit test for the property 'QrCode'
        }

    }

}
