/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BaseRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BaseRuleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BaseRule
        //private BaseRule instance;

        public BaseRuleTests()
        {
            // TODO uncomment below to create an instance of BaseRule
            //instance = new BaseRule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BaseRule
        /// </summary>
        [Fact]
        public void BaseRuleInstanceTest()
        {
            // TODO uncomment below to test "IsType" BaseRule
            //Assert.IsType<BaseRule>(instance);
        }

        /// <summary>
        /// Test deserialize a DateTimeRule from type BaseRule
        /// </summary>
        [Fact]
        public void DateTimeRuleDeserializeFromBaseRuleTest()
        {
            // TODO uncomment below to test deserialize a DateTimeRule from type BaseRule
            //Assert.IsType<BaseRule>(JsonConvert.DeserializeObject<BaseRule>(new DateTimeRule().ToJson()));
        }
        /// <summary>
        /// Test deserialize a EmailRule from type BaseRule
        /// </summary>
        [Fact]
        public void EmailRuleDeserializeFromBaseRuleTest()
        {
            // TODO uncomment below to test deserialize a EmailRule from type BaseRule
            //Assert.IsType<BaseRule>(JsonConvert.DeserializeObject<BaseRule>(new EmailRule().ToJson()));
        }
        /// <summary>
        /// Test deserialize a LocationRule from type BaseRule
        /// </summary>
        [Fact]
        public void LocationRuleDeserializeFromBaseRuleTest()
        {
            // TODO uncomment below to test deserialize a LocationRule from type BaseRule
            //Assert.IsType<BaseRule>(JsonConvert.DeserializeObject<BaseRule>(new LocationRule().ToJson()));
        }
        /// <summary>
        /// Test deserialize a ScanOptionRule from type BaseRule
        /// </summary>
        [Fact]
        public void ScanOptionRuleDeserializeFromBaseRuleTest()
        {
            // TODO uncomment below to test deserialize a ScanOptionRule from type BaseRule
            //Assert.IsType<BaseRule>(JsonConvert.DeserializeObject<BaseRule>(new ScanOptionRule().ToJson()));
        }
        /// <summary>
        /// Test deserialize a UserRoleRule from type BaseRule
        /// </summary>
        [Fact]
        public void UserRoleRuleDeserializeFromBaseRuleTest()
        {
            // TODO uncomment below to test deserialize a UserRoleRule from type BaseRule
            //Assert.IsType<BaseRule>(JsonConvert.DeserializeObject<BaseRule>(new UserRoleRule().ToJson()));
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
