/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CropRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CropRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CropRequest
        //private CropRequest instance;

        public CropRequestTests()
        {
            // TODO uncomment below to create an instance of CropRequest
            //instance = new CropRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CropRequest
        /// </summary>
        [Fact]
        public void CropRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CropRequest
            //Assert.IsType<CropRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ImageDataUrl'
        /// </summary>
        [Fact]
        public void ImageDataUrlTest()
        {
            // TODO unit test for the property 'ImageDataUrl'
        }
        /// <summary>
        /// Test the property 'MaxWidth'
        /// </summary>
        [Fact]
        public void MaxWidthTest()
        {
            // TODO unit test for the property 'MaxWidth'
        }
        /// <summary>
        /// Test the property 'MaxHeight'
        /// </summary>
        [Fact]
        public void MaxHeightTest()
        {
            // TODO unit test for the property 'MaxHeight'
        }
        /// <summary>
        /// Test the property 'AspectRatio'
        /// </summary>
        [Fact]
        public void AspectRatioTest()
        {
            // TODO unit test for the property 'AspectRatio'
        }

    }

}
