/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CropResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CropResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CropResponse
        //private CropResponse instance;

        public CropResponseTests()
        {
            // TODO uncomment below to create an instance of CropResponse
            //instance = new CropResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CropResponse
        /// </summary>
        [Fact]
        public void CropResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CropResponse
            //Assert.IsType<CropResponse>(instance);
        }


        /// <summary>
        /// Test the property 'ImageDataUrl'
        /// </summary>
        [Fact]
        public void ImageDataUrlTest()
        {
            // TODO unit test for the property 'ImageDataUrl'
        }

    }

}
