/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DatasetPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DatasetPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DatasetPostRequest
        //private DatasetPostRequest instance;

        public DatasetPostRequestTests()
        {
            // TODO uncomment below to create an instance of DatasetPostRequest
            //instance = new DatasetPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DatasetPostRequest
        /// </summary>
        [Fact]
        public void DatasetPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DatasetPostRequest
            //Assert.IsType<DatasetPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PayloadId'
        /// </summary>
        [Fact]
        public void PayloadIdTest()
        {
            // TODO unit test for the property 'PayloadId'
        }

    }

}
