/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DatasetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DatasetResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DatasetResponse
        //private DatasetResponse instance;

        public DatasetResponseTests()
        {
            // TODO uncomment below to create an instance of DatasetResponse
            //instance = new DatasetResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DatasetResponse
        /// </summary>
        [Fact]
        public void DatasetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DatasetResponse
            //Assert.IsType<DatasetResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'LocalizedNames'
        /// </summary>
        [Fact]
        public void LocalizedNamesTest()
        {
            // TODO unit test for the property 'LocalizedNames'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'PayloadId'
        /// </summary>
        [Fact]
        public void PayloadIdTest()
        {
            // TODO unit test for the property 'PayloadId'
        }
        /// <summary>
        /// Test the property 'RuleIds'
        /// </summary>
        [Fact]
        public void RuleIdsTest()
        {
            // TODO unit test for the property 'RuleIds'
        }
        /// <summary>
        /// Test the property 'ViewableByAssociatedUserTypes'
        /// </summary>
        [Fact]
        public void ViewableByAssociatedUserTypesTest()
        {
            // TODO unit test for the property 'ViewableByAssociatedUserTypes'
        }
        /// <summary>
        /// Test the property 'UsageCount'
        /// </summary>
        [Fact]
        public void UsageCountTest()
        {
            // TODO unit test for the property 'UsageCount'
        }

    }

}
