/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DatasetRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DatasetRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DatasetRequest
        //private DatasetRequest instance;

        public DatasetRequestTests()
        {
            // TODO uncomment below to create an instance of DatasetRequest
            //instance = new DatasetRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DatasetRequest
        /// </summary>
        [Fact]
        public void DatasetRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DatasetRequest
            //Assert.IsType<DatasetRequest>(instance);
        }

        /// <summary>
        /// Test deserialize a DatasetPostRequest from type DatasetRequest
        /// </summary>
        [Fact]
        public void DatasetPostRequestDeserializeFromDatasetRequestTest()
        {
            // TODO uncomment below to test deserialize a DatasetPostRequest from type DatasetRequest
            //Assert.IsType<DatasetRequest>(JsonConvert.DeserializeObject<DatasetRequest>(new DatasetPostRequest().ToJson()));
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'LocalizedNames'
        /// </summary>
        [Fact]
        public void LocalizedNamesTest()
        {
            // TODO unit test for the property 'LocalizedNames'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'PayloadId'
        /// </summary>
        [Fact]
        public void PayloadIdTest()
        {
            // TODO unit test for the property 'PayloadId'
        }
        /// <summary>
        /// Test the property 'RuleIds'
        /// </summary>
        [Fact]
        public void RuleIdsTest()
        {
            // TODO unit test for the property 'RuleIds'
        }
        /// <summary>
        /// Test the property 'ViewableByAssociatedUserTypes'
        /// </summary>
        [Fact]
        public void ViewableByAssociatedUserTypesTest()
        {
            // TODO unit test for the property 'ViewableByAssociatedUserTypes'
        }

    }

}
