/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DateTimeRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DateTimeRuleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DateTimeRule
        //private DateTimeRule instance;

        public DateTimeRuleTests()
        {
            // TODO uncomment below to create an instance of DateTimeRule
            //instance = new DateTimeRule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DateTimeRule
        /// </summary>
        [Fact]
        public void DateTimeRuleInstanceTest()
        {
            // TODO uncomment below to test "IsType" DateTimeRule
            //Assert.IsType<DateTimeRule>(instance);
        }


        /// <summary>
        /// Test the property 'BegDate'
        /// </summary>
        [Fact]
        public void BegDateTest()
        {
            // TODO unit test for the property 'BegDate'
        }
        /// <summary>
        /// Test the property 'BegTime'
        /// </summary>
        [Fact]
        public void BegTimeTest()
        {
            // TODO unit test for the property 'BegTime'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property 'IsIgnoreTimeZone'
        /// </summary>
        [Fact]
        public void IsIgnoreTimeZoneTest()
        {
            // TODO unit test for the property 'IsIgnoreTimeZone'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
