/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceInfo
        //private DeviceInfo instance;

        public DeviceInfoTests()
        {
            // TODO uncomment below to create an instance of DeviceInfo
            //instance = new DeviceInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceInfo
        /// </summary>
        [Fact]
        public void DeviceInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceInfo
            //Assert.IsType<DeviceInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Fact]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'DeviceName'
        /// </summary>
        [Fact]
        public void DeviceNameTest()
        {
            // TODO unit test for the property 'DeviceName'
        }
        /// <summary>
        /// Test the property 'DeviceVersion'
        /// </summary>
        [Fact]
        public void DeviceVersionTest()
        {
            // TODO unit test for the property 'DeviceVersion'
        }
        /// <summary>
        /// Test the property 'AppVersion'
        /// </summary>
        [Fact]
        public void AppVersionTest()
        {
            // TODO unit test for the property 'AppVersion'
        }
        /// <summary>
        /// Test the property 'AppBuild'
        /// </summary>
        [Fact]
        public void AppBuildTest()
        {
            // TODO unit test for the property 'AppBuild'
        }
        /// <summary>
        /// Test the property 'SchemaVer'
        /// </summary>
        [Fact]
        public void SchemaVerTest()
        {
            // TODO unit test for the property 'SchemaVer'
        }

    }

}
