/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EmailRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailRequest
        //private EmailRequest instance;

        public EmailRequestTests()
        {
            // TODO uncomment below to create an instance of EmailRequest
            //instance = new EmailRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailRequest
        /// </summary>
        [Fact]
        public void EmailRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailRequest
            //Assert.IsType<EmailRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
