/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FaceTypesVerifyContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FaceTypesVerifyContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FaceTypesVerifyContent
        //private FaceTypesVerifyContent instance;

        public FaceTypesVerifyContentTests()
        {
            // TODO uncomment below to create an instance of FaceTypesVerifyContent
            //instance = new FaceTypesVerifyContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FaceTypesVerifyContent
        /// </summary>
        [Fact]
        public void FaceTypesVerifyContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" FaceTypesVerifyContent
            //Assert.IsType<FaceTypesVerifyContent>(instance);
        }


        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Fact]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
