/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FacePhotoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FacePhotoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FacePhotoResponse
        //private FacePhotoResponse instance;

        public FacePhotoResponseTests()
        {
            // TODO uncomment below to create an instance of FacePhotoResponse
            //instance = new FacePhotoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FacePhotoResponse
        /// </summary>
        [Fact]
        public void FacePhotoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" FacePhotoResponse
            //Assert.IsType<FacePhotoResponse>(instance);
        }


        /// <summary>
        /// Test the property 'ImageDataURL'
        /// </summary>
        [Fact]
        public void ImageDataURLTest()
        {
            // TODO unit test for the property 'ImageDataURL'
        }

    }

}
