/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GeofenceData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeofenceDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeofenceData
        //private GeofenceData instance;

        public GeofenceDataTests()
        {
            // TODO uncomment below to create an instance of GeofenceData
            //instance = new GeofenceData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeofenceData
        /// </summary>
        [Fact]
        public void GeofenceDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeofenceData
            //Assert.IsType<GeofenceData>(instance);
        }

        /// <summary>
        /// Test deserialize a GeofenceCircleData from type GeofenceData
        /// </summary>
        [Fact]
        public void GeofenceCircleDataDeserializeFromGeofenceDataTest()
        {
            // TODO uncomment below to test deserialize a GeofenceCircleData from type GeofenceData
            //Assert.IsType<GeofenceData>(JsonConvert.DeserializeObject<GeofenceData>(new GeofenceCircleData().ToJson()));
        }
        /// <summary>
        /// Test deserialize a GeofencePolygonData from type GeofenceData
        /// </summary>
        [Fact]
        public void GeofencePolygonDataDeserializeFromGeofenceDataTest()
        {
            // TODO uncomment below to test deserialize a GeofencePolygonData from type GeofenceData
            //Assert.IsType<GeofenceData>(JsonConvert.DeserializeObject<GeofenceData>(new GeofencePolygonData().ToJson()));
        }
        /// <summary>
        /// Test deserialize a GeofenceRectangleData from type GeofenceData
        /// </summary>
        [Fact]
        public void GeofenceRectangleDataDeserializeFromGeofenceDataTest()
        {
            // TODO uncomment below to test deserialize a GeofenceRectangleData from type GeofenceData
            //Assert.IsType<GeofenceData>(JsonConvert.DeserializeObject<GeofenceData>(new GeofenceRectangleData().ToJson()));
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
