/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RefreshTokenRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RefreshTokenRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RefreshTokenRequest
        //private RefreshTokenRequest instance;

        public RefreshTokenRequestTests()
        {
            // TODO uncomment below to create an instance of RefreshTokenRequest
            //instance = new RefreshTokenRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RefreshTokenRequest
        /// </summary>
        [Fact]
        public void RefreshTokenRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RefreshTokenRequest
            //Assert.IsType<RefreshTokenRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

    }

}
