/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ScanContentListItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScanContentListItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScanContentListItem
        //private ScanContentListItem instance;

        public ScanContentListItemTests()
        {
            // TODO uncomment below to create an instance of ScanContentListItem
            //instance = new ScanContentListItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScanContentListItem
        /// </summary>
        [Fact]
        public void ScanContentListItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScanContentListItem
            //Assert.IsType<ScanContentListItem>(instance);
        }


        /// <summary>
        /// Test the property 'DatasetId'
        /// </summary>
        [Fact]
        public void DatasetIdTest()
        {
            // TODO unit test for the property 'DatasetId'
        }
        /// <summary>
        /// Test the property 'DatasetName'
        /// </summary>
        [Fact]
        public void DatasetNameTest()
        {
            // TODO unit test for the property 'DatasetName'
        }
        /// <summary>
        /// Test the property 'PayloadType'
        /// </summary>
        [Fact]
        public void PayloadTypeTest()
        {
            // TODO unit test for the property 'PayloadType'
        }
        /// <summary>
        /// Test the property 'PayloadName'
        /// </summary>
        [Fact]
        public void PayloadNameTest()
        {
            // TODO unit test for the property 'PayloadName'
        }

    }

}
