/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SmacGenerateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SmacGenerateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SmacGenerateRequest
        //private SmacGenerateRequest instance;

        public SmacGenerateRequestTests()
        {
            // TODO uncomment below to create an instance of SmacGenerateRequest
            //instance = new SmacGenerateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SmacGenerateRequest
        /// </summary>
        [Fact]
        public void SmacGenerateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SmacGenerateRequest
            //Assert.IsType<SmacGenerateRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Metadatas'
        /// </summary>
        [Fact]
        public void MetadatasTest()
        {
            // TODO unit test for the property 'Metadatas'
        }

    }

}
