/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UploadPhotoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UploadPhotoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UploadPhotoResponse
        //private UploadPhotoResponse instance;

        public UploadPhotoResponseTests()
        {
            // TODO uncomment below to create an instance of UploadPhotoResponse
            //instance = new UploadPhotoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UploadPhotoResponse
        /// </summary>
        [Fact]
        public void UploadPhotoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UploadPhotoResponse
            //Assert.IsType<UploadPhotoResponse>(instance);
        }


        /// <summary>
        /// Test the property 'PhotoDataURL'
        /// </summary>
        [Fact]
        public void PhotoDataURLTest()
        {
            // TODO unit test for the property 'PhotoDataURL'
        }

    }

}
