/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UploadPhotoRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UploadPhotoRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UploadPhotoRequest
        //private UploadPhotoRequest instance;

        public UploadPhotoRequestTests()
        {
            // TODO uncomment below to create an instance of UploadPhotoRequest
            //instance = new UploadPhotoRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UploadPhotoRequest
        /// </summary>
        [Fact]
        public void UploadPhotoRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UploadPhotoRequest
            //Assert.IsType<UploadPhotoRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ImageBase64'
        /// </summary>
        [Fact]
        public void ImageBase64Test()
        {
            // TODO unit test for the property 'ImageBase64'
        }

    }

}
