/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserRoleRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserRoleRuleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserRoleRule
        //private UserRoleRule instance;

        public UserRoleRuleTests()
        {
            // TODO uncomment below to create an instance of UserRoleRule
            //instance = new UserRoleRule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserRoleRule
        /// </summary>
        [Fact]
        public void UserRoleRuleInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserRoleRule
            //Assert.IsType<UserRoleRule>(instance);
        }


        /// <summary>
        /// Test the property 'UserRoles'
        /// </summary>
        [Fact]
        public void UserRolesTest()
        {
            // TODO unit test for the property 'UserRoles'
        }
        /// <summary>
        /// Test the property 'IsInverse'
        /// </summary>
        [Fact]
        public void IsInverseTest()
        {
            // TODO unit test for the property 'IsInverse'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
