/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing VerifyTokenResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifyTokenResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifyTokenResponse
        //private VerifyTokenResponse instance;

        public VerifyTokenResponseTests()
        {
            // TODO uncomment below to create an instance of VerifyTokenResponse
            //instance = new VerifyTokenResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifyTokenResponse
        /// </summary>
        [Fact]
        public void VerifyTokenResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifyTokenResponse
            //Assert.IsType<VerifyTokenResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Audiences'
        /// </summary>
        [Fact]
        public void AudiencesTest()
        {
            // TODO unit test for the property 'Audiences'
        }

    }

}
