/*
 * SMAC API
 *
 * SMAC ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing VerifyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifyResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifyResponse
        //private VerifyResponse instance;

        public VerifyResponseTests()
        {
            // TODO uncomment below to create an instance of VerifyResponse
            //instance = new VerifyResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifyResponse
        /// </summary>
        [Fact]
        public void VerifyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifyResponse
            //Assert.IsType<VerifyResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'ReferenceImage'
        /// </summary>
        [Fact]
        public void ReferenceImageTest()
        {
            // TODO unit test for the property 'ReferenceImage'
        }

    }

}
